"""Editorial data for Medical Law Türkiye glossary pages.

Each entry supplies term-specific material to the shared renderer. Legal outcomes
remain fact-dependent; the linked primary sources are the publication authority.
"""

TERMS = [
    {
        "term": "Medical Malpractice", "tr": "Tıbbi Uygulama Hatası / Malpraktis", "category": "liability",
        "definition": "Medical malpractice is a legal assessment of whether healthcare conduct departed from the applicable professional standard and caused compensable harm. A poor outcome alone does not establish malpractice.",
        "question": "The central inquiry is not simply whether treatment failed, but what the provider did, what a competent provider should have done in the same circumstances, and whether that difference caused the documented injury.",
        "nuance": "Diagnosis, consent, operative technique, follow-up and the response to complications may each require separate analysis. Liability and the value of a claim cannot be inferred from photographs alone.",
        "evidence": ["complete clinical record and operative notes", "pre-treatment condition and consent material", "dated photographs and independent examinations", "messages showing the provider's response after the problem arose"],
        "related": ["standard-of-care", "causation", "burden-of-proof"],
    },
    {
        "term": "Health Law", "tr": "Sağlık Hukuku", "category": "framework",
        "definition": "Health law is the field governing relationships among patients, professionals, facilities, regulators and payers. In Türkiye it draws on public, private, criminal, consumer and data-protection rules rather than one single health-law code.",
        "question": "A health-law review first identifies the provider, facility type, treatment setting and legal relationship because those facts affect the competent authority, procedure and available remedies.",
        "nuance": "The same medical event can raise different questions at once, including patient rights, contractual performance, professional discipline, administrative responsibility and personal-data processing.",
        "evidence": ["identity and licence details of every provider", "facility authorisations and invoices", "medical record and consent documents", "complaints or correspondence with public authorities"],
        "related": ["patient-rights-regulation", "medical-malpractice", "consumer-law"],
    },
    {
        "term": "Informed Consent", "tr": "Aydınlatılmış Onam", "category": "consent",
        "definition": "Informed consent is the patient's decision after receiving understandable information relevant to the proposed intervention. The review concerns the explanation and decision-making process, not merely whether a form carries a signature.",
        "question": "The practical question is what information was provided about the procedure, material risks, alternatives and likely course, in which language, at what time, and whether the patient could ask questions freely.",
        "nuance": "The content required depends on the intervention and the patient's circumstances. A generic form may be evidence, but it does not by itself establish the quality or timing of the explanation.",
        "evidence": ["signed consent form and every attachment", "clinic messages and translated material", "consultation notes showing risks and alternatives", "timeline between explanation and intervention"],
        "related": ["capacity-to-consent", "right-to-refuse-treatment", "assumption-of-risk"],
    },
    {
        "term": "Statute of Limitations", "tr": "Zamanaşımı", "category": "procedure",
        "definition": "A statute of limitations is a time rule that can restrict when a claim or application may be pursued. There is no safe universal deadline for every Turkish medical dispute.",
        "question": "The correct calculation depends on the defendant, public or private setting, legal basis, relevant event and when material facts became known. Criminal, civil, consumer and administrative routes may follow different rules.",
        "nuance": "Online summaries that quote one period can be dangerous. A lawyer should calculate the applicable route from the documents and preserve the earliest plausible deadline.",
        "evidence": ["exact treatment and discharge dates", "date the injury or cause became known", "identity and status of the facility", "prior notices, complaints, mediation or court filings"],
        "related": ["mediation", "consumer-law", "turkish-code-of-obligations"],
    },
    {
        "term": "Pecuniary Damages", "tr": "Maddi Tazminat", "category": "damages",
        "definition": "Pecuniary damages concern financial loss that can be evidenced and linked to the event, such as treatment expenses, travel, care needs or lost earnings. They are assessed from proof, not a standard tariff.",
        "question": "A damages analysis asks which costs were reasonably incurred, which future costs are supported by medical evidence, and what income difference can be demonstrated because of the injury.",
        "nuance": "Invoices establish payment, but causation and reasonableness still matter. Currency, tax, employment status and third-party payments may also affect the calculation.",
        "evidence": ["itemised medical and pharmacy invoices", "travel and accommodation receipts", "pay records and tax documents", "medical plan for future treatment or care"],
        "related": ["loss-of-earnings", "future-medical-expenses", "damage-mitigation-obligation"],
    },
    {
        "term": "Non-Pecuniary Damages", "tr": "Manevi Tazminat", "category": "damages",
        "definition": "Non-pecuniary damages address non-financial harm such as pain, distress and effects on bodily integrity or quality of life. They are distinct from reimbursement of invoices and lost income.",
        "question": "The court evaluates the proven event, severity, duration, personal consequences and the parties' circumstances rather than applying a publicly fixed table for every injury.",
        "nuance": "The description of suffering should remain evidence-led and proportionate. A serious complication does not automatically establish fault, and fault does not predetermine an award.",
        "evidence": ["contemporaneous treatment and mental-health records", "dated recovery photographs", "statements describing daily-life limitations", "duration and permanence findings from clinicians"],
        "related": ["pecuniary-damages", "permanent-disability-rate", "bereavement-damages"],
    },
    {
        "term": "Complication", "tr": "Komplikasyon", "category": "clinical",
        "definition": "A complication is an adverse event associated with an illness or intervention. Calling an outcome a complication does not, by itself, decide whether care was appropriate or whether liability exists.",
        "question": "The review separates the occurrence of the event from the provider's duties to assess risk, inform the patient, detect warning signs and respond in accordance with the circumstances.",
        "nuance": "A recognised risk may occur without negligence, while a recognised complication can still be mishandled. The timing of symptoms and the clinical response are therefore central.",
        "evidence": ["risk information provided before treatment", "observations and vital-sign records", "messages reporting the first warning signs", "referral, revision and emergency-treatment records"],
        "related": ["informed-consent", "post-operative-care", "causation"],
    },
    {
        "term": "Power of Attorney", "tr": "Vekaletname", "category": "procedure",
        "definition": "A power of attorney is an authorisation allowing another person, including a lawyer, to perform specified legal acts for the grantor. Its required form and wording depend on the intended act.",
        "question": "For a cross-border matter, the review identifies which steps must be authorised, where the document will be signed, whether notarisation or consular formalities apply, and whether a translation is required.",
        "nuance": "A power of attorney is not the claim itself and does not guarantee that every authority will accept broad wording. The scope should match the actual representation needed.",
        "evidence": ["valid identity and consistent name spelling", "draft authority wording", "notarial or consular execution record", "apostille and certified translation where applicable"],
        "related": ["health-tourism", "mediation", "right-to-access-medical-records"],
    },
    {
        "term": "Court of Cassation", "tr": "Yargıtay", "category": "procedure",
        "definition": "The Court of Cassation, Yargıtay, is Türkiye's highest appellate court for ordinary civil and criminal justice. Its decisions help explain how legal rules are applied, but a cited decision must be checked in context.",
        "question": "A useful precedent review compares the chamber, date, legal issue, facts and procedural posture with the present dispute instead of relying on an isolated quotation.",
        "nuance": "Not every result is a binding rule for every medical case. Decisions can turn on evidence, facility type, contract characterisation or procedural error.",
        "evidence": ["full official decision rather than a summary", "chamber, docket and decision numbers", "facts matching the proposed comparison", "later decisions or legislative changes affecting the point"],
        "related": ["burden-of-proof", "medical-service-contract", "causation"],
    },
    {
        "term": "Forensic Medicine Institute", "tr": "Adli Tıp Kurumu (ATK)", "category": "evidence",
        "definition": "The Forensic Medicine Institute, Adli Tıp Kurumu, is an official expert institution within Türkiye's justice system. It may provide specialised opinions when requested by competent judicial authorities.",
        "question": "The evidential issue is what question the authority asked, which records the experts received, which specialty examined the matter and whether the report addresses the disputed causal and clinical points.",
        "nuance": "An ATK report is not automatically present in every dispute and should not be described as the only possible expert evidence. The procedure and weight of reports depend on the case.",
        "evidence": ["authority's referral questions", "complete file transmitted for examination", "expert report and any dissenting opinion", "objections or supplementary-report requests"],
        "related": ["medical-board-report", "standard-of-care", "causation"],
    },
    {
        "term": "Burden of Proof", "tr": "İspat Yükü", "category": "procedure",
        "definition": "The burden of proof determines which party bears the consequence when a legally relevant fact is not established. Its allocation depends on the claim, defence and governing procedural rules.",
        "question": "A medical dispute should be broken into propositions: duty, information, breach, injury, causation and loss. Different evidence and allocation rules may apply to each proposition.",
        "nuance": "It is unsafe to say that one party always proves everything. Consent documentation, possession of records and the legal character of the relationship may affect the analysis.",
        "evidence": ["pleadings identifying each disputed fact", "records controlled by the provider", "expert material addressing clinical propositions", "documents proving injury and financial loss"],
        "related": ["causation", "informed-consent", "medical-malpractice"],
    },
    {
        "term": "Health Tourism", "tr": "Sağlık Turizmi", "category": "tourism",
        "definition": "International health tourism covers healthcare obtained in Türkiye by qualifying patients who travel from abroad, together with regulated support services. Providers and intermediaries may need specific authorisation.",
        "question": "A legal review identifies the licensed treatment provider, any intermediary, the services each promised, the payment chain and the communications aimed at the international patient.",
        "nuance": "Foreign residence does not create an automatic compensation route. Contract, jurisdiction, applicable law, authorisation and evidence must be assessed from the actual transaction.",
        "evidence": ["provider and intermediary authorisation details", "package offer and payment trail", "translations and international-patient forms", "travel, transfer and accommodation communications"],
        "related": ["consumer-law", "medical-service-contract", "power-of-attorney"],
    },
    {
        "term": "Duty of Care", "tr": "Özen Yükümlülüğü", "category": "clinical",
        "definition": "Duty of care describes the diligence expected within a healthcare relationship. The content of that duty is determined by the provider's role, the patient's condition and the circumstances at the relevant time.",
        "question": "The case question is what precautions, assessment, technique, monitoring or referral were reasonably required, and whether the provider's documented conduct met that expectation.",
        "nuance": "The duty is not a guarantee of cure. It is evaluated using contemporaneous facts and appropriate expertise, not hindsight alone.",
        "evidence": ["treatment plan and clinical assessment", "professional role of each participant", "monitoring and escalation records", "independent specialty opinion"],
        "related": ["standard-of-care", "surgical-negligence", "post-operative-care"],
    },
    {
        "term": "Turkish Code of Obligations", "tr": "Türk Borçlar Kanunu (TBK)", "category": "contract",
        "definition": "The Turkish Code of Obligations, Law No. 6098, contains general rules on contracts, performance, breach, tort and damages. It is a central source for many private healthcare disputes.",
        "question": "The relevant provisions depend on how the relationship and alleged wrong are characterised. A legal review connects the facts to specific duties rather than citing the Code as a single malpractice rule.",
        "nuance": "The official consolidated text should be checked for amendments. Consumer, procedural, patient-rights and sector-specific rules may apply alongside the Code.",
        "evidence": ["contract and incorporated terms", "proof of payment and promised services", "chronology of performance and alleged breach", "documented loss linked to the breach"],
        "related": ["contractual-liability", "tortious-liability", "medical-service-contract"],
    },
    {
        "term": "Mediation", "tr": "Arabuluculuk", "category": "consumer",
        "definition": "Mediation is a confidential facilitated negotiation conducted by a registered neutral. In some categories of Turkish disputes, applying to mediation is a procedural precondition before filing suit.",
        "question": "The first task is to determine whether mandatory mediation applies, identify every proper party and prepare a settlement position supported by medical and financial evidence.",
        "nuance": "Mediation is not a judgment on negligence and an application does not guarantee settlement. Limitation and procedural deadlines still require separate attention.",
        "evidence": ["correct legal names and addresses of parties", "concise event chronology", "key medical proof and quantified losses", "authority to negotiate and settlement parameters"],
        "related": ["consumer-law", "statute-of-limitations", "power-of-attorney"],
    },
    {
        "term": "Criminal Liability", "tr": "Cezai Sorumluluk", "category": "criminal",
        "definition": "Criminal liability concerns conduct meeting the elements of an offence under Turkish criminal law. It is separate from civil compensation and professional or administrative review.",
        "question": "Authorities examine the alleged act, mental element or negligence standard, causal result and admissible evidence under criminal procedure; an adverse medical outcome alone is insufficient.",
        "nuance": "A criminal complaint should not be presented as a shortcut to compensation. Classification, investigation and charging decisions belong to competent authorities.",
        "evidence": ["original medical record and forensic material", "precise event and symptom chronology", "witness identities and communications", "complaint, expert and prosecutor documents"],
        "related": ["medical-malpractice", "causation", "forensic-medicine-institute"],
    },
    {
        "term": "Standard of Care", "tr": "Tıbbi Standart", "category": "clinical",
        "definition": "The standard of care is the professional benchmark used to evaluate clinical conduct in the circumstances. It is specific to the procedure, specialty, patient and time of treatment.",
        "question": "The analysis compares documented decisions and actions with the reasonable clinical approach supported by appropriate expertise and applicable rules, while accounting for available information and urgency.",
        "nuance": "Guidelines can inform the benchmark but do not mechanically decide every case. Departure, causation and damage remain distinct questions.",
        "evidence": ["contemporaneous examination and test results", "operative or treatment technique records", "relevant professional guidance", "independent opinion from the appropriate specialty"],
        "related": ["duty-of-care", "complication", "medical-malpractice"],
    },
    {
        "term": "Consumer Law", "tr": "Tüketici Hukuku", "category": "consumer",
        "definition": "Consumer law regulates qualifying transactions between consumers and commercial or professional providers. Some private healthcare disputes may fall within this framework, depending on the parties and transaction.",
        "question": "A review checks who supplied and paid for each service, whether the patient acted as a consumer, what was promised and which consumer forum or pre-action process may apply.",
        "nuance": "It is not safe to assume every medical dispute belongs in a consumer court. Public treatment, insurance arrangements and the defendant's legal status can change the route.",
        "evidence": ["invoice and payment recipient", "advertising and pre-contract information", "service agreement and package terms", "provider's commercial identity and facility status"],
        "related": ["mediation", "breach-of-contract", "health-tourism"],
    },
    {
        "term": "Medical Board Report", "tr": "Sağlık Kurulu Raporu / Heyet Raporu", "category": "evidence",
        "definition": "A medical board report is a formal assessment produced by a committee or authorised health board for a defined purpose. Its scope, issuing body and methodology determine its relevance.",
        "question": "The legal team must identify what the report was asked to assess, which specialties participated, what records were reviewed and whether the conclusions answer the disputed issue.",
        "nuance": "A board report is not interchangeable with every expert opinion and does not automatically prove negligence or causation. The intended administrative or legal use matters.",
        "evidence": ["referral purpose and authority", "membership and specialties of the board", "tests and records considered", "reasoned findings and any objection route"],
        "related": ["permanent-disability-rate", "forensic-medicine-institute", "causation"],
    },
    {
        "term": "Causation", "tr": "İlliyet Bağı / Nedensellik Bağı", "category": "liability",
        "definition": "Causation is the legally relevant connection between alleged conduct and the claimed injury or loss. It is separate from proving that conduct fell below the required standard.",
        "question": "The analysis asks what would probably have happened without the alleged act, whether other causes explain the outcome and which claimed losses follow from the proven injury.",
        "nuance": "Chronology can support causation but timing alone is not proof. Pre-existing conditions, natural risks, later treatment and intervening events may require expert evaluation.",
        "evidence": ["pre-treatment baseline and medical history", "precise onset and progression timeline", "diagnostic evidence linking mechanism and injury", "independent opinion addressing alternative causes"],
        "related": ["medical-malpractice", "complication", "burden-of-proof"],
    },
    {
        "term": "Permanent Disability Rate", "tr": "Maluliyet Oranı", "category": "evidence",
        "definition": "A permanent disability rate is a formal percentage assessment of lasting functional impairment made under an applicable methodology. It is not the same as a negligence finding or a compensation amount.",
        "question": "The assessment depends on diagnosis, stabilisation, functional examination, the governing schedule and the purpose for which the report is requested.",
        "nuance": "Different legal or insurance contexts may use different criteria. A percentage should never be copied from an informal online estimate.",
        "evidence": ["final diagnosis and treatment history", "functional examination findings", "applicable assessment methodology", "occupation and daily-life evidence where legally relevant"],
        "related": ["medical-board-report", "loss-of-earnings", "future-medical-expenses"],
    },
    {
        "term": "Temporary Incapacity", "tr": "Geçici İş Göremezlik", "category": "damages",
        "definition": "Temporary incapacity describes a medically supported period during which injury limits work or ordinary functions before recovery or stabilisation. Its legal effect depends on the claim and evidence.",
        "question": "The review links certified restrictions and recovery periods to actual employment, income and care consequences rather than assuming every absence is compensable.",
        "nuance": "A sick note, payroll loss and medical causation answer different parts of the analysis. Overlapping benefits or employer payments must be documented.",
        "evidence": ["medical certificates with defined restrictions", "employment schedule and absence records", "pay slips and benefit statements", "rehabilitation and return-to-work evidence"],
        "related": ["loss-of-earnings", "permanent-disability-rate", "pecuniary-damages"],
    },
    {
        "term": "Iatrogenic Injury", "tr": "İyatrojenik Zarar", "category": "clinical",
        "definition": "An iatrogenic injury is harm associated with medical examination or treatment. The descriptive label does not establish that the harm resulted from negligence.",
        "question": "The legal inquiry identifies the mechanism of injury, whether it was an inherent risk or avoidable event, how it was recognised and whether the response met the applicable standard.",
        "nuance": "Using the term as a synonym for malpractice is inaccurate. Consent, technique, causation and management must be analysed separately.",
        "evidence": ["procedure and anaesthesia records", "first objective sign of injury", "recognition and corrective-treatment timeline", "specialist opinion on mechanism and avoidability"],
        "related": ["complication", "surgical-negligence", "causation"],
    },
    {
        "term": "Nosocomial Infection", "tr": "Hastane Enfeksiyonu", "category": "clinical",
        "definition": "A nosocomial or healthcare-associated infection is an infection connected with healthcare exposure and not simply any infection noticed after treatment. Classification and responsibility require clinical analysis.",
        "question": "The review considers timing, organism, surveillance, infection-control measures, patient risk factors and the speed and adequacy of diagnosis and treatment.",
        "nuance": "The occurrence of infection does not automatically prove a hygiene breach. Conversely, a known infection risk does not excuse inadequate prevention or response.",
        "evidence": ["admission and symptom timeline", "culture and laboratory results", "antibiotic and isolation records", "facility infection-control investigation if available"],
        "related": ["standard-of-care", "post-operative-care", "causation"],
    },
    {
        "term": "Wrong-Site Surgery", "tr": "Yanlış Taraf Ameliyatı", "category": "clinical",
        "definition": "Wrong-site surgery involves an intervention on the wrong patient, procedure, body part or side. It is a serious safety event requiring precise factual and institutional review.",
        "question": "The investigation reconstructs scheduling, consent, site marking, team verification, the operative record and the facility's response after discovery.",
        "nuance": "The legal parties and consequences cannot be determined from the label alone. Individual conduct, organisational systems, causation and corrective care each require evidence.",
        "evidence": ["booking and theatre list", "site-marking and team-check records", "consent and operative report", "incident report and corrective-treatment plan"],
        "related": ["surgical-negligence", "vicarious-liability", "medical-malpractice"],
    },
    {
        "term": "Surgical Negligence", "tr": "Cerrahi İhmal", "category": "clinical",
        "definition": "Surgical negligence is an allegation that planning, performance or perioperative management fell below the required professional standard and caused harm. It is not established by dissatisfaction alone.",
        "question": "A proper review separates pre-operative assessment, technique, team responsibilities, post-operative monitoring and informed consent before considering causation.",
        "nuance": "Revision surgery may provide evidence of anatomy or damage, but it does not automatically prove the first operation was negligent.",
        "evidence": ["pre-operative plan and imaging", "anaesthesia and operative records", "implant or device traceability", "revision findings and independent specialty opinion"],
        "related": ["standard-of-care", "post-operative-care", "iatrogenic-injury"],
    },
    {
        "term": "Post-Operative Care", "tr": "Ameliyat Sonrası Bakım Yükümlülüğü", "category": "clinical",
        "definition": "Post-operative care covers monitoring, instructions, communication and treatment after an operation. The required response depends on the procedure, symptoms and foreseeable risks.",
        "question": "The review asks what warning signs were reported, when they were reported, what advice or examination followed and whether escalation was timely.",
        "nuance": "A complication may arise despite appropriate surgery, yet delay or inadequate follow-up can create a separate legal issue.",
        "evidence": ["discharge instructions in the patient's language", "observation and follow-up records", "timestamped calls, messages and photographs", "emergency referral and readmission documents"],
        "related": ["complication", "duty-of-care", "damage-mitigation-obligation"],
    },
    {
        "term": "Off-Label Drug Use", "tr": "Endikasyon Dışı İlaç Kullanımı", "category": "clinical",
        "definition": "Off-label use means using a medicine outside aspects of its authorised product information. It is not automatically improper, but may raise regulatory, clinical and consent questions.",
        "question": "The review examines the clinical reason, evidence base, applicable Ministry or medicines-authority process, dosage, monitoring and information provided to the patient.",
        "nuance": "The legal analysis must distinguish authorised product status from professional judgment and from unauthorised or unsafe practice.",
        "evidence": ["medicine name, dose and indication", "prescription and administration record", "clinical rationale and monitoring plan", "information and consent documentation"],
        "related": ["informed-consent", "standard-of-care", "medical-malpractice"],
    },
    {
        "term": "Medical Device Liability", "tr": "Tıbbi Cihaz Sorumluluğu", "category": "product",
        "definition": "Medical device liability concerns harm alleged to arise from a device's design, manufacture, instructions, supply, implantation or use. Multiple actors and legal bases may be involved.",
        "question": "The review identifies the exact device, manufacturer and supply chain, separates product performance from implantation technique, and preserves evidence before removal or disposal.",
        "nuance": "A device revision or recall does not automatically prove an individual claim. Traceability, defect, use, causation and warnings must be assessed.",
        "evidence": ["device label, serial or lot number", "implant card and operative record", "instructions, warnings and recall information", "removed device, imaging and expert analysis where available"],
        "related": ["surgical-negligence", "consumer-law", "causation"],
    },
    {
        "term": "Cosmetic Surgery Regulation", "tr": "Estetik Cerrahi Mevzuatı", "category": "tourism",
        "definition": "Cosmetic surgery in Türkiye is governed by general healthcare, professional, facility, patient-rights, advertising and contract rules rather than one statute promising a particular aesthetic result.",
        "question": "A review checks provider qualifications, facility authorisation, the scope of the intervention, information given, marketing claims and the actual agreement with the patient.",
        "nuance": "Describing every cosmetic procedure as a guaranteed-result contract is too broad. Legal characterisation depends on the undertaking and facts.",
        "evidence": ["surgeon identity and specialty", "facility licence and international authorisation", "advertisement and promised result", "consent, plan and operative record"],
        "related": ["health-tourism", "medical-service-contract", "informed-consent"],
    },
    {
        "term": "Loss of Earnings", "tr": "Kazanç Kaybı", "category": "damages",
        "definition": "Loss of earnings is a claimed financial difference between income that would probably have been earned and income actually received because of the proven injury.",
        "question": "The analysis connects medical restrictions to a credible work history and distinguishes past absence, reduced capacity and future earning effects.",
        "nuance": "Projected income requires more than a personal estimate. Employment pattern, self-employment records, taxes, benefits and career contingencies can matter.",
        "evidence": ["employment contract and role requirements", "pay slips, tax and business records", "medical work restrictions", "employer confirmation and return-to-work history"],
        "related": ["temporary-incapacity", "permanent-disability-rate", "pecuniary-damages"],
    },
    {
        "term": "Future Medical Expenses", "tr": "Gelecekteki Tedavi Giderleri", "category": "damages",
        "definition": "Future medical expenses are reasonably anticipated treatment, rehabilitation, medication or care costs linked to the injury. They must be supported rather than guessed.",
        "question": "The review asks what care is medically likely, when it may occur, how long it may continue and whether the proposed cost reflects an appropriate pathway.",
        "nuance": "A commercial quotation is not the same as medical necessity. Uncertainty, alternative treatments and currency should be explained transparently.",
        "evidence": ["independent prognosis and treatment plan", "itemised provider quotations", "therapy, medication and assistive-device needs", "expected timing and duration of care"],
        "related": ["pecuniary-damages", "permanent-disability-rate", "damage-mitigation-obligation"],
    },
    {
        "term": "Loss of Consortium", "tr": "Aile Bütünlüğünün Bozulması Zararı", "category": "damages",
        "definition": "Loss of consortium is a comparative-law expression for harm to close family relationships after severe injury. Turkish claims should be framed under the remedies and standing recognised by Turkish law, not imported labels alone.",
        "question": "The legal review identifies who may claim, the nature and seriousness of the relational impact, and the Turkish legal basis appropriate to the facts.",
        "nuance": "A spouse or relative does not automatically receive a separate award whenever a patient is injured. Relationship, severity, evidence and governing doctrine matter.",
        "evidence": ["proof of the close family relationship", "medical evidence of severity and duration", "specific changes to care and family life", "evidence supporting the claimant's own harm"],
        "related": ["non-pecuniary-damages", "wrongful-death", "bereavement-damages"],
    },
    {
        "term": "Wrongful Death", "tr": "Haksız Fiil Sonucu Ölüm", "category": "damages",
        "definition": "Wrongful death is a general English label for civil consequences when a legally responsible act causes death. Turkish law determines who may claim and which material or moral losses are recoverable.",
        "question": "The review separates responsibility for the death from dependency, support, funeral cost and moral-damage questions concerning eligible relatives.",
        "nuance": "Death after treatment does not itself prove malpractice. Cause of death, standard of care and the status of each claimant require independent proof.",
        "evidence": ["death certificate and complete final treatment record", "forensic or expert causation material", "family-status and dependency documents", "funeral and support-loss evidence"],
        "related": ["bereavement-damages", "causation", "pecuniary-damages"],
    },
    {
        "term": "Bereavement Damages", "tr": "Ölüm Nedeniyle Manevi Tazminat", "category": "damages",
        "definition": "Bereavement damages is an English shorthand for non-pecuniary claims connected with a death. Turkish law does not apply a universal fixed bereavement payment to every relative.",
        "question": "The analysis identifies eligible close persons, the relationship, the circumstances of death and the Turkish legal basis for claimed moral harm.",
        "nuance": "This subject should not be reduced to a calculator or guaranteed range. Judicial assessment is fact-sensitive and separate from material dependency loss.",
        "evidence": ["civil-registry relationship documents", "records proving the cause and circumstances of death", "evidence of the relationship's closeness", "separate documentation of material dependency if claimed"],
        "related": ["wrongful-death", "non-pecuniary-damages", "loss-of-consortium"],
    },
    {
        "term": "Damage Mitigation Obligation", "tr": "Zararı Azaltma Yükümlülüğü", "category": "liability",
        "definition": "Damage mitigation describes the expectation that a harmed person take reasonable steps to avoid preventable worsening of loss. It does not require unsafe treatment or unlimited personal expense.",
        "question": "The review compares medical advice, available options, urgency, cost and the patient's actual decisions to determine whether an alleged avoidable increase is supported.",
        "nuance": "A defendant must not simply blame the patient for a difficult recovery. Reasonableness is assessed in the real circumstances, including access and language barriers.",
        "evidence": ["medical advice and referrals received", "appointments attended or unavailable", "reasons for declining or delaying treatment", "steps taken to protect health and preserve records"],
        "related": ["contributory-negligence", "future-medical-expenses", "post-operative-care"],
    },
    {
        "term": "Interest on Damages", "tr": "Tazminata İşleyen Faiz", "category": "damages",
        "definition": "Interest on damages concerns an additional monetary consequence over time. The applicable basis, rate and start date depend on the claim, debtor, default rules and current legislation.",
        "question": "A calculation must identify the principal amount, legal character of the debt, relevant notice or event, judgment terms and any statutory rate changes.",
        "nuance": "Publishing a fixed percentage is unsafe because rates and legal rules can change. The current official text and case-specific dates should be used.",
        "evidence": ["principal-loss calculation", "notice or default documentation", "filing and judgment dates", "current official rate source and payment history"],
        "related": ["pecuniary-damages", "turkish-code-of-obligations", "breach-of-contract"],
    },
    {
        "term": "Lump Sum vs. Periodic Payment", "tr": "Toplu / Dönemsel Ödeme", "category": "damages",
        "definition": "Lump-sum and periodic payment describe different ways future loss or care may be funded. The available form in a Turkish dispute depends on legal authority, the claim and any settlement structure.",
        "question": "The comparison considers certainty, inflation, longevity, care timing, enforcement and whether the proposed arrangement is a court remedy or negotiated settlement term.",
        "nuance": "It should not be stated that a Turkish court will always order or accept one method. The procedural and substantive basis must be verified.",
        "evidence": ["future-loss and care schedule", "life and treatment contingencies", "inflation and discount assumptions", "draft settlement or requested judgment terms"],
        "related": ["future-medical-expenses", "permanent-disability-rate", "mediation"],
    },
    {
        "term": "Malpractice Insurance", "tr": "Mesleki Sorumluluk Sigortası", "category": "insurance",
        "definition": "Medical professional liability insurance may respond to covered claims against insured healthcare professionals under the governing policy and compulsory-insurance rules. Coverage is not identical to liability.",
        "question": "The review identifies the insured person, policy period, alleged act, notification requirements, exclusions and whether another facility or insurer is involved.",
        "nuance": "The existence of insurance does not prove negligence or guarantee full payment. Policy limits, defence arrangements and coverage disputes may affect recovery.",
        "evidence": ["provider and employer identity", "policy or compulsory-insurance information", "treatment and claim dates", "notice, reservation and insurer correspondence"],
        "related": ["vicarious-liability", "joint-and-several-liability", "medical-malpractice"],
    },
    {
        "term": "Social Security Recourse", "tr": "SGK Rücu Hakkı", "category": "insurance",
        "definition": "Social Security Institution recourse concerns circumstances in which SGK may seek recovery of expenditure from a legally responsible party under applicable social-security rules.",
        "question": "The analysis distinguishes the patient's own claim from SGK's institutional rights and identifies which benefits, treatment costs and responsibility provisions are engaged.",
        "nuance": "Recourse is not automatic in every malpractice allegation. The statutory basis, SGK payment and responsibility findings require verification.",
        "evidence": ["SGK payment and benefit records", "identity of the allegedly responsible party", "incident and treatment documentation", "official recourse notice or proceeding"],
        "related": ["pecuniary-damages", "malpractice-insurance", "joint-and-several-liability"],
    },
    {
        "term": "Contractual Liability", "tr": "Sözleşmeden Doğan Sorumluluk", "category": "contract",
        "definition": "Contractual liability arises when a binding obligation is not performed as required and the legal conditions for responsibility and loss are met. The contract's content is therefore central.",
        "question": "A healthcare review identifies the contracting parties, promised services, standard of performance, alleged breach, causation and recoverable loss.",
        "nuance": "A disappointing result is not automatically a contractual breach, and an advertisement is not always the complete contract. Clinical duties and mandatory patient protections may supplement the terms.",
        "evidence": ["signed agreement and incorporated documents", "advertising or written promises", "invoice and payment recipient", "performance record and documented loss"],
        "related": ["breach-of-contract", "medical-service-contract", "turkish-code-of-obligations"],
    },
    {
        "term": "Tortious Liability", "tr": "Haksız Fiilden Doğan Sorumluluk", "category": "liability",
        "definition": "Tortious liability concerns responsibility for an unlawful act causing damage independently of, or alongside, a contract. Turkish law sets the required elements and defences.",
        "question": "The review asks what protected interest was infringed, whether the conduct was unlawful and attributable, how it caused harm and what damage is proven.",
        "nuance": "Contract and tort labels can overlap in healthcare facts. Choosing a legal basis affects proof, limitation and remedy issues and should not be done from a template.",
        "evidence": ["event and actor chronology", "clinical evidence of the alleged act", "causation analysis", "documents proving each claimed loss"],
        "related": ["contractual-liability", "causation", "turkish-code-of-obligations"],
    },
    {
        "term": "Vicarious Liability", "tr": "Adam Çalıştıranın Sorumluluğu", "category": "liability",
        "definition": "Vicarious liability is a comparative label for circumstances in which an employer or organisation may be responsible for acts connected with personnel or organisational duties. Turkish statutory requirements control the result.",
        "question": "The analysis maps who employed, directed or contracted each person, what task was performed and whether organisational safeguards or supervision are legally relevant.",
        "nuance": "A clinic is not automatically liable for every act of every doctor, and the word 'strict' should not replace analysis of the statutory basis and relationships.",
        "evidence": ["employment and contractor relationships", "facility organisational chart", "allocation of clinical responsibilities", "policies, supervision and incident records"],
        "related": ["joint-and-several-liability", "strict-liability", "wrong-site-surgery"],
    },
    {
        "term": "Joint and Several Liability", "tr": "Müteselsil Sorumluluk", "category": "liability",
        "definition": "Joint and several liability can allow a claimant to pursue multiple responsible parties under rules governing the same damage. It does not make every participant responsible automatically.",
        "question": "The review identifies each actor's legal basis, contribution to the same harm, available defences and any rights of allocation or recourse among defendants.",
        "nuance": "The surgeon, facility, intermediary, manufacturer and insurer occupy different legal positions. Their names should not be grouped without evidence.",
        "evidence": ["identity and role of every participant", "contracts between providers and intermediaries", "causal contribution evidence", "payments, settlements and recourse documents"],
        "related": ["vicarious-liability", "medical-device-liability", "contractual-liability"],
    },
    {
        "term": "Strict Liability", "tr": "Kusursuz Sorumluluk", "category": "liability",
        "definition": "Strict or no-fault liability refers to exceptional legal bases where responsibility does not require proof of ordinary fault in the usual way. It is not a general rule for all Turkish medical outcomes.",
        "question": "The analysis must identify the exact statutory doctrine, protected risk, responsible person and causal link before fault-independent liability is considered.",
        "nuance": "Calling a hospital 'strictly liable' for any complication is inaccurate. Organisational, employer, product and contractual liability have distinct requirements.",
        "evidence": ["specific statutory basis relied upon", "identity and control of the relevant risk", "event and causation record", "documents establishing the defendant's legal status"],
        "related": ["vicarious-liability", "medical-device-liability", "tortious-liability"],
    },
    {
        "term": "Contributory Negligence", "tr": "Müterafik Kusur", "category": "liability",
        "definition": "Contributory negligence describes conduct by the injured person alleged to have contributed to the occurrence or extent of damage. It is evaluated in context and does not erase provider duties automatically.",
        "question": "The review asks what instruction was actually given, whether it was understandable and reasonable, what the patient did, and what causal difference that conduct made.",
        "nuance": "Language, access to care, emergency symptoms and contradictory advice may be important. A bare statement that the patient 'did not comply' is not enough.",
        "evidence": ["clear discharge and medication instructions", "proof of translation or explanation", "patient messages and appointment history", "expert view on the effect of the alleged conduct"],
        "related": ["damage-mitigation-obligation", "post-operative-care", "causation"],
    },
    {
        "term": "Force Majeure", "tr": "Mücbir Sebep", "category": "contract",
        "definition": "Force majeure concerns an extraordinary external event alleged to prevent performance or break legal responsibility. Its effect depends on the governing rule, contract and actual impact.",
        "question": "The review tests foreseeability, avoidability, causal effect, notice and whether alternative performance or protective steps remained possible.",
        "nuance": "An emergency, shortage or natural event is not automatically a complete defence. The event must be connected to the specific obligation and consequences claimed.",
        "evidence": ["contract clause and governing rule", "official record of the external event", "operational effect on the specific service", "notice and mitigation steps taken by the provider"],
        "related": ["breach-of-contract", "contractual-liability", "damage-mitigation-obligation"],
    },
    {
        "term": "Assumption of Risk", "tr": "Riskin Bilinerek Kabulü", "category": "consent",
        "definition": "Assumption of risk is a comparative expression for a person's informed acceptance of a known risk. It is not a blanket waiver of negligent treatment under Turkish law.",
        "question": "The review asks which specific risk was explained, whether the patient understood and accepted it, and whether the actual harm arose despite appropriate care or from a separate breach.",
        "nuance": "Consent to a recognised complication does not mean consent to negligent technique, inadequate monitoring or delayed treatment.",
        "evidence": ["risk-specific consent material", "consultation and translation records", "clinical evidence of how the harm occurred", "records of recognition and management after the event"],
        "related": ["informed-consent", "complication", "standard-of-care"],
    },
    {
        "term": "Breach of Contract", "tr": "Sözleşmenin İhlali", "category": "contract",
        "definition": "A breach of contract is failure to perform a binding contractual obligation as required. The first task is to identify the obligation, not to assume every unwanted medical result was promised against.",
        "question": "The review compares the written and legally implied terms with actual performance, then examines notice, causation, loss and any remedy or defence.",
        "nuance": "Consent doctrine, clinical negligence and contractual promises are related but distinct. Generic consent-case language should not be substituted for contract analysis.",
        "evidence": ["complete contract and terms", "advertising, quotation and written assurances", "payment and service-delivery record", "correspondence about correction, refund or refusal"],
        "related": ["contractual-liability", "medical-service-contract", "consumer-law"],
    },
    {
        "term": "Medical Service Contract", "tr": "Tıbbi Hizmet Sözleşmesi", "category": "contract",
        "definition": "A medical service contract records or implies obligations between a patient and provider. Its legal classification depends on the parties, service and actual undertaking; labels such as mandate or work contract are not automatic.",
        "question": "The review identifies who contracted, what result or process was promised, which mandatory professional duties apply and how the agreement interacts with consumer and patient-rights rules.",
        "nuance": "Elective or aesthetic treatment does not by itself prove a guaranteed-result obligation. The exact promise and legal context must be examined.",
        "evidence": ["signed treatment agreement", "written treatment plan and quotation", "provider and payment identities", "communications describing expected result and limitations"],
        "related": ["breach-of-contract", "contractual-liability", "cosmetic-surgery-regulation"],
    },
    {
        "term": "Patient Rights Regulation", "tr": "Hasta Hakları Yönetmeliği", "category": "rights",
        "definition": "The Patient Rights Regulation is an official Turkish framework addressing matters such as access to services, information, consent, privacy, records and complaint mechanisms.",
        "question": "A legal review connects the patient's specific experience to the current official provision and to any other applicable legislation rather than citing patient rights only in general terms.",
        "nuance": "The Regulation supports important protections, but the remedy and competent route vary. The current consolidated text should be consulted.",
        "evidence": ["specific right and official provision relied upon", "facility record of the event", "request, refusal or complaint correspondence", "patient-rights unit or authority response"],
        "related": ["informed-consent", "privacy-of-medical-data", "patient-advocate"],
    },
    {
        "term": "Right to Refuse Treatment", "tr": "Tedaviyi Reddetme Hakkı", "category": "consent",
        "definition": "The right to refuse treatment protects a competent patient's decision not to accept or continue an intervention, subject to the applicable legal framework and emergency or other lawful exceptions.",
        "question": "The review considers capacity, information, voluntariness, documentation, the treatment context and whether the refusal was respected or lawfully overridden.",
        "nuance": "A refusal should not be treated as informed merely because it was signed. The patient may need understandable information about consequences and alternatives.",
        "evidence": ["refusal form and clinical note", "information about consequences and alternatives", "capacity assessment where relevant", "record of later treatment or emergency circumstances"],
        "related": ["capacity-to-consent", "emergency-exception-to-consent", "informed-consent"],
    },
    {
        "term": "Right to Second Opinion", "tr": "İkinci Görüş Hakkı", "category": "rights",
        "definition": "A second opinion is an independent clinical assessment sought to understand diagnosis or treatment options. Patient-rights rules support access to information and choice within the applicable healthcare setting.",
        "question": "For a dispute, the issue is whether records were available, whether the second clinician had adequate information and what the later opinion actually establishes.",
        "nuance": "A different medical opinion is not automatically proof that the first provider was negligent. The reasons, timing and evidence behind the difference matter.",
        "evidence": ["complete record supplied for review", "independent clinician's reasoned opinion", "new tests or imaging considered", "comparison with the original diagnosis and plan"],
        "related": ["right-to-access-medical-records", "standard-of-care", "medical-board-report"],
    },
    {
        "term": "Privacy of Medical Data", "tr": "Tıbbi Veri Gizliliği", "category": "data",
        "definition": "Medical data privacy concerns the lawful and secure processing of identifiable health information. Health data receives special protection under Türkiye's personal-data framework.",
        "question": "A review identifies the data controller, data categories, legal basis, purpose, recipients, cross-border transfers, security measures and response to the patient's request.",
        "nuance": "Consent is not the only possible legal basis, and a privacy complaint is distinct from a malpractice claim. Current KVKK rules and decisions should be checked.",
        "evidence": ["privacy notice and consent records", "data-access or correction request", "identity of recipients and transfer trail", "security incident and controller response"],
        "related": ["right-to-access-medical-records", "patient-rights-regulation", "health-tourism"],
    },
    {
        "term": "Right to Access Medical Records", "tr": "Tıbbi Kayıtlara Erişim Hakkı", "category": "data",
        "definition": "Patients have important rights concerning access to health information and records under patient-rights and data-protection rules. The precise scope, method and lawful restrictions should be checked in the current official texts.",
        "question": "The review identifies what was requested, from which controller or facility, in what form, how identity was verified and what response or refusal was given.",
        "nuance": "Describing access as unlimited or 'absolute' is too broad. Third-party information, legal restrictions and secure-delivery requirements can affect the response.",
        "evidence": ["dated written access request", "proof of delivery and identity verification", "inventory of missing record categories", "facility or controller response and stated legal basis"],
        "related": ["privacy-of-medical-data", "patient-rights-regulation", "power-of-attorney"],
    },
    {
        "term": "Patient Advocate", "tr": "Hasta Hakları Birimi", "category": "rights",
        "definition": "Patient-rights units within the Turkish health system receive and process certain patient concerns. They are an institutional complaint channel, not the patient's personal lawyer.",
        "question": "The practical review determines whether the unit is the appropriate route, what issue was submitted, which documents were provided and what written outcome followed.",
        "nuance": "Using a patient-rights unit does not necessarily replace urgent medical care, limitation protection, mediation or a formal legal process.",
        "evidence": ["complaint reference and submission", "supporting clinical documents", "facility or unit response", "record of escalation to another authority"],
        "related": ["patient-rights-regulation", "right-to-access-medical-records", "mediation"],
    },
    {
        "term": "Vulnerable Patient", "tr": "Savunmasız Hasta", "category": "rights",
        "definition": "A vulnerable patient may face added barriers because of age, disability, capacity, language, dependency or circumstances. The relevant duties depend on the particular barrier and legal context.",
        "question": "The review asks what support was reasonably needed for communication, consent, safeguarding, access or continuity and what the provider actually arranged.",
        "nuance": "Vulnerability should not be used as a vague label. The patient's autonomy remains central, and support must respond to individual needs.",
        "evidence": ["documented communication or accessibility need", "interpreter or support-person arrangements", "capacity and safeguarding records", "evidence of how barriers affected care or consent"],
        "related": ["capacity-to-consent", "minor-patient-consent", "informed-consent"],
    },
    {
        "term": "Minor Patient Consent", "tr": "Küçük Hastada Onam", "category": "consent",
        "definition": "Consent for a minor requires attention to legal representation, the child's maturity and participation, the intervention and any urgent exception. A parent's signature is not the entire analysis.",
        "question": "The review identifies who held parental or guardianship authority, what was explained to the child and representative, and whether the decision reflected the applicable rule.",
        "nuance": "Age alone should not erase the child's voice, while a minor's agreement may not replace legally required representative consent. Emergencies require separate assessment.",
        "evidence": ["proof of parent or guardian authority", "age-appropriate information material", "child and representative consent records", "clinical urgency and capacity documentation"],
        "related": ["capacity-to-consent", "emergency-exception-to-consent", "vulnerable-patient"],
    },
    {
        "term": "Capacity to Consent", "tr": "Rıza Ehliyeti", "category": "consent",
        "definition": "Capacity to consent concerns whether a person can understand, retain, weigh and communicate a decision about the proposed intervention in the relevant circumstances.",
        "question": "The assessment is decision-specific and time-specific. It considers the information provided, communication support, effects of illness or medication and the person's actual reasoning.",
        "nuance": "A diagnosis, age or disability does not automatically establish incapacity. Equally, a signature does not prove capacity where material concerns existed.",
        "evidence": ["contemporaneous capacity assessment", "information and communication adjustments", "medication and clinical state at decision time", "representative or emergency basis relied upon"],
        "related": ["informed-consent", "minor-patient-consent", "right-to-refuse-treatment"],
    },
    {
        "term": "Emergency Exception to Consent", "tr": "Acil Durumda Onam İstisnası", "category": "consent",
        "definition": "An emergency exception may permit necessary intervention when valid consent cannot be obtained in time and delay would create serious risk. Its scope is limited by the actual emergency and applicable law.",
        "question": "The review reconstructs urgency, capacity, availability of a representative, alternatives, the intervention's necessity and documentation of the decision.",
        "nuance": "The word 'emergency' is not a blanket justification for unrelated or elective procedures. Once circumstances permit, ordinary information and consent duties resume.",
        "evidence": ["arrival condition and vital signs", "capacity and representative-contact attempts", "clinical reasons delay was unsafe", "scope of emergency treatment and later consent"],
        "related": ["capacity-to-consent", "right-to-refuse-treatment", "minor-patient-consent"],
    },
]
